//! Data models for the Task Retrospective system.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use uuid::Uuid;

// ============================================================================
// TaskRetrospective — the core learning record
// ============================================================================

/// A structured post-execution analysis of a task, capturing everything
/// the agent did (tool calls, files, commits) and what we learned from it.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskRetrospective {
    pub id: Uuid,
    pub task_id: Uuid,
    pub agent_execution_id: Option<Uuid>,
    pub project_id: Option<Uuid>,
    /// Outcome classification
    pub outcome: RetrospectiveOutcome,
    /// Confidence score from TaskExecutionReport (0.0–1.0)
    pub confidence_score: f64,
    pub duration_secs: f64,
    pub cost_usd: f64,
    /// Total tool calls during execution
    pub tool_call_count: u32,
    /// Per-tool breakdown: {"Edit": 5, "Bash": 3, ...}
    pub tool_call_breakdown: HashMap<String, u32>,
    /// Number of tool calls that returned errors
    pub error_count: u32,
    /// Last error message (for retry context)
    pub last_error: Option<String>,
    /// Files modified during execution
    pub files_modified: Vec<String>,
    /// Commit SHAs produced
    pub commits: Vec<String>,
    /// UUIDs of Notes auto-generated by this retrospective
    pub notes_generated: Vec<Uuid>,
    /// Serialized CohortComparison (None if cohort too small)
    pub cohort_json: Option<String>,
    pub created_at: DateTime<Utc>,
}

// ============================================================================
// Outcome
// ============================================================================

/// How the task execution ended.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum RetrospectiveOutcome {
    Success,
    Failure { reason: String },
    Partial { completed: usize, total: usize },
}

impl RetrospectiveOutcome {
    /// String label for Neo4j storage.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Success => "success",
            Self::Failure { .. } => "failure",
            Self::Partial { .. } => "partial",
        }
    }

    pub fn is_success(&self) -> bool {
        matches!(self, Self::Success)
    }

    pub fn from_neo4j(outcome: &str, reason: Option<String>) -> Self {
        match outcome {
            "success" => Self::Success,
            "failure" => Self::Failure {
                reason: reason.unwrap_or_default(),
            },
            "partial" => Self::Partial {
                completed: 0,
                total: 0,
            },
            _ => Self::Success,
        }
    }
}

impl std::fmt::Display for RetrospectiveOutcome {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Success => write!(f, "success"),
            Self::Failure { reason } => write!(f, "failure: {reason}"),
            Self::Partial {
                completed, total, ..
            } => write!(f, "partial: {completed}/{total}"),
        }
    }
}

// ============================================================================
// Cohort comparison (statistical analysis results)
// ============================================================================

/// Statistical comparison of this execution against a historical cohort
/// of similar tasks (same project, overlapping tags/files).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CohortComparison {
    /// How many historical retrospectives were in the cohort
    pub cohort_size: usize,
    /// What criteria selected the cohort
    pub cohort_criteria: String,
    /// Duration comparison
    pub duration: MetricComparison,
    /// Cost comparison
    pub cost: MetricComparison,
    /// Confidence comparison
    pub confidence: MetricComparison,
    /// Tools used at unusual ratios vs cohort
    pub tool_anomalies: Vec<ToolAnomaly>,
    /// Files with historical failure signals
    pub file_risk_signals: Vec<FileRiskSignal>,
}

/// How a single metric compares to the cohort distribution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MetricComparison {
    pub current: f64,
    pub cohort_mean: f64,
    pub cohort_std: f64,
    /// How many standard deviations from the mean
    pub z_score: f64,
    /// Percentile within the cohort (0.0–1.0)
    pub percentile: f64,
}

impl MetricComparison {
    /// Compute from current value and a slice of cohort values.
    pub fn compute(current: f64, cohort: &[f64]) -> Self {
        if cohort.is_empty() {
            return Self {
                current,
                cohort_mean: 0.0,
                cohort_std: 0.0,
                z_score: 0.0,
                percentile: 0.5,
            };
        }

        let n = cohort.len() as f64;
        let mean = cohort.iter().sum::<f64>() / n;
        let variance = cohort.iter().map(|v| (v - mean).powi(2)).sum::<f64>() / n;
        let std = variance.sqrt();

        let z_score = if std > f64::EPSILON {
            (current - mean) / std
        } else {
            0.0
        };

        let below = cohort.iter().filter(|&&v| v <= current).count();
        let percentile = below as f64 / n;

        Self {
            current,
            cohort_mean: mean,
            cohort_std: std,
            z_score,
            percentile,
        }
    }
}

/// A tool used at an unusual ratio compared to the cohort.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolAnomaly {
    pub tool_name: String,
    /// Ratio of this tool vs total calls in current execution
    pub current_ratio: f64,
    /// Mean ratio in the cohort
    pub cohort_mean_ratio: f64,
    /// "higher" or "lower"
    pub direction: String,
}

/// A file with a historical failure signal.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileRiskSignal {
    pub file_path: String,
    /// Fraction of past retrospectives touching this file that failed
    pub failure_rate: f64,
    /// Signal type: "high_failure_correlation", "hot_file"
    pub signal: String,
}

// ============================================================================
// ToolTrace — intermediate structure from collector
// ============================================================================

/// Extracted tool call trace from ChatEventRecords.
#[derive(Debug, Clone, Default)]
pub struct ToolTrace {
    pub tool_calls: Vec<ToolCallEntry>,
    pub tool_call_count: u32,
    pub tool_call_breakdown: HashMap<String, u32>,
    pub error_count: u32,
    pub last_error: Option<String>,
}

/// A single tool call with its input and output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallEntry {
    pub seq: i64,
    pub tool_name: String,
    pub action: Option<String>,
    pub input_json: String,
    pub output_json: Option<String>,
    pub is_error: bool,
    pub timestamp: DateTime<Utc>,
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_outcome_roundtrip() {
        let outcomes = vec![
            RetrospectiveOutcome::Success,
            RetrospectiveOutcome::Failure {
                reason: "build failed".to_string(),
            },
            RetrospectiveOutcome::Partial {
                completed: 3,
                total: 5,
            },
        ];
        for outcome in &outcomes {
            let json = serde_json::to_string(outcome).unwrap();
            let deserialized: RetrospectiveOutcome = serde_json::from_str(&json).unwrap();
            assert_eq!(*outcome, deserialized);
        }
    }

    #[test]
    fn test_outcome_as_str() {
        assert_eq!(RetrospectiveOutcome::Success.as_str(), "success");
        assert_eq!(
            RetrospectiveOutcome::Failure { reason: "x".into() }.as_str(),
            "failure"
        );
        assert_eq!(
            RetrospectiveOutcome::Partial {
                completed: 1,
                total: 2
            }
            .as_str(),
            "partial"
        );
    }

    #[test]
    fn test_metric_comparison_compute() {
        let cohort = vec![10.0, 20.0, 30.0, 40.0, 50.0];
        let mc = MetricComparison::compute(30.0, &cohort);
        assert!((mc.cohort_mean - 30.0).abs() < 0.01);
        assert!(mc.z_score.abs() < 0.01); // exactly at the mean
        assert!((mc.percentile - 0.6).abs() < 0.01); // 3 of 5 are <= 30
    }

    #[test]
    fn test_metric_comparison_empty_cohort() {
        let mc = MetricComparison::compute(42.0, &[]);
        assert_eq!(mc.cohort_mean, 0.0);
        assert_eq!(mc.percentile, 0.5);
    }
}
